Enhancement/state badges
bcgov/repomountie pull request #116
Opened 2020-10-07 21:11 UTC by AndrewJun97

2020-10-09 21:02 UTC, patricksimonian commented on __tests__/repository.test.ts
> +import { addLicenseIfRequired, addMinistryTopicIfRequired, addSecurityComplianceInfoIfRequired, addWordsMatterIfRequire, fixDeprecatedComplianceStatus, requestStatusBadgeIfRequired } from '../src/lib
prettier should make this prettier

2020-10-09 21:16 UTC, patricksimonian reviewed
You'll probably want to make an assertion that this thing doesn't open up multiple issues (in an infinite loop)

2020-10-09 21:16 UTC, patricksimonian commented on __tests__/repository.test.ts
> +        fetchFileContent.mockReturnValueOnce(`Here's a project badge. https://img.shields.io/badge/Lifecycle-Inspiration-007EC6`);
you should test against valid markdown image `![img](https://img.shields.io/badge/Lifecycle-Inspiration-007EC6)`

2020-10-09 21:16 UTC, patricksimonian commented on __tests__/repository.test.ts
> +    it('A repo without a project state badge has project state badge issue created', async () => {
an invalid project state badge.

2020-10-09 21:16 UTC, patricksimonian commented on __tests__/repository.test.ts
> +        fetchFileContent.mockReturnValueOnce(`Here's a random badge that is not a project badge. https://img.shields.io/badge/Lifecycle-Testing-007EC6`);
i'd suggest having a md fixtured file with several project state badges just to make sure your assertions work correctly. 

Also as above, reference the links as images!

2020-10-09 21:16 UTC, patricksimonian commented on __tests__/repository.test.ts
> +        fetchFileContent.mockReturnValueOnce(0);
why does this return zero?

2020-10-09 21:16 UTC, patricksimonian commented on templates/state-badges.md
> +Hello, it looks like the readme doesn't have project state badges. Please check out [STATE_BADGE_URL] for more information on project state badges.
this is going to need work but good effort so far. We will rope in Mark and or Steph for comms

2020-10-09 21:16 UTC, patricksimonian commented on src/libs/repository.ts
> +    const re = new RegExp(REGEXP.state_badge);
abstract this into its own function and test it seperately.

2020-10-21 17:06 UTC, patricksimonian commented on __tests__/repository.test.ts
> +
should we have a test verifying if an issue is already created it doesn't create another issue 🤔

2020-10-21 17:13 UTC, patricksimonian commented on __tests__/repository.test.ts
> +    it('Returns false when the string is ![img](https://img.shields.io/badge/Lifecycle-test-007EC6)', () => {
not a great title for a test. To me this reads it its a true/false output tied directly to the `Inspiration` vs `test` where this is more testing valid and invalid values.

2020-10-21 17:13 UTC, patricksimonian commented on __tests__/repository.test.ts
> +        expect(doesContentHaveStateBadge('![img](https://img.shields.io/badge/Lifecycle-Inspiration-007EC6)')).toBe(true);
test all valid values

2020-10-21 17:14 UTC, patricksimonian commented on src/libs/repository.ts
> +    await context.github.issues.create({
should check if issue has already been created

2020-10-21 17:14 UTC, patricksimonian requested changes
almost there!

2020-10-21 23:14 UTC, AndrewJun97 commented on __tests__/repository.test.ts
> +
Yup, this case has been tested: "A repo with an open project state badge issue should not have another project state badge issue created"

2020-10-21 23:16 UTC, AndrewJun97 commented on src/libs/repository.ts
> +    await context.github.issues.create({
This check is done using the query

2020-10-22 21:47 UTC, patricksimonian approved these changes
looks good. just one small refactor _could be done_

2020-10-22 21:47 UTC, patricksimonian commented on src/libs/repository.ts
> +    }
this could be simplified :) 
```js
if (issuesResponse.data.total_count && issuesResponse.data.total_count > 0) { 
  return; 
};
```

2020-10-23 20:36 UTC, patricksimonian commented on templates/state-badges.md
> +Hello, it looks like the readme for this project doesn't have a project state badge. Please check out [Project State Badges](https://github.com/bcgov/repomountie/blob/master/doc/state-badges.md) for
```suggestion
## No project state badge found in your readme!
Hello! I scanned your readme and could not find a project state badge. A project state badge will provide contributors to your project as well as other stakeholders (platform services, executive) insight into the lifecycle of your repository.

## What is a Project State Badge?
It is a simple image that neatly describes your projects stage in its lifecycle. More information can be found in the [project state badges documentation.](https://github.com/bcgov/repomountie/blob/master/doc/state-badges.md) for more information.

## What do I need to do?
I suggest you make PR into your README.md and add a project state badge near the top where it is easy for your users to pick it up :). Once it is merged feel free to close this issue. I will not open up a new one :) 
```

2020-10-23 20:37 UTC, AndrewJun97 commented on src/libs/repository.ts
> +    }
I think i'll keep this as is to be consistent with the rest of Jason's code

2020-11-02 18:09 UTC, jleach approved these changes

2020-11-03 19:59 UTC, merged