add repository schedule to remind inactive repos
bcgov/repomountie pull request #136
Opened 2021-05-04 16:23 UTC by junminahn

This is intended to start to organize which repositories are actively maintained or not.
It opens an issue on repositories that haven't been updated in 180 days to help identify organizations that are no longer maintained.

2021-05-04 17:00 UTC, wenzowski requested changes

2021-05-04 17:00 UTC, wenzowski commented on templates/inactive_repo_reminder.md
> +If this repository isn't actively developed anymore and you want to make this repository read-only, it is recommended to archive this repository.
We probably want to collaborate on the text content of this issue.

```suggestion
This issue is a kind reminder that your repository has been inactive for <%- daysInactive %> days. Some repositories are maintained in accordance with business requirements that infrequently change thus appearing inactive, and some repositories are inactive because they are unmaintained.

To help differentiate products that are unmaintained from products that do not require frequent maintenance, repomountie will open an issue whenever a repository has not been updated in <%- daysInactive %> days.

If this product is being actively maintained, please close this issue.
If this repository isn't being actively maintained anymore, please archive this repository.

Thank you for your help ensuring effective governance of our open-source ecosystem!
```

2021-05-04 17:03 UTC, junminahn commented on package-lock.json
> +      "version": "1.2.13",
good point! I will revert the changes on `package-lock.json`

2021-05-04 17:19 UTC, junminahn commented on templates/inactive_repo_reminder.md
> +If this repository isn't actively developed anymore and you want to make this repository read-only, it is recommended to archive this repository.
It sounds much better. I will update the content.

2021-05-04 17:20 UTC, junminahn commented
@wenzowski thank you for reviewing! I made changes based on your feedback.

2021-05-04 19:22 UTC, wenzowski approved these changes
Thanks @junminahn! Looking forward to seeing what @jleach has to add :)

2021-05-04 19:30 UTC, wenzowski commented
This is now a `+91 −3` single-feature patch, and the diff is hopefully a bit more reviewable as a result.

2021-05-04 20:15 UTC, jleach approved these changes

2021-05-10 22:17 UTC, jleach commented
I'll merge and deploy this shortly. I'm just releasing a different change and want to see how it goes first.

2021-05-10 23:33 UTC, merged

2021-05-11 23:17 UTC, jleach commented
This is deploying now. Will take a while to grind through all 1000 repos.