add snapshot test for created issue template
bcgov/repomountie pull request #151
Opened 2021-05-13 00:17 UTC by jlangy

creation of a snapshot test for inactive issue template and updated
header files.

2021-05-14 18:22 UTC, wenzowski requested changes
Good snapshot test of the renderer, and perhaps the mock data we're using could be improved?

2021-05-14 18:22 UTC, wenzowski commented on __tests__/templates.test.ts
> +        daysInactiveLimit: 2,
While this does work, and demonstrates correct interpolation into the snapshot, shouldn't the mock data be representative of the conditions under which the template will be rendered (ie. `daysInactive > daysInactiveLimit`)?
```suggestion
        daysInactive: 14,
        daysInactiveLimit: 7,
```

2021-05-17 16:09 UTC, jlangy commented on __tests__/templates.test.ts
> +        daysInactiveLimit: 2,
I see, yes that's a good point I will update it

2021-05-25 21:37 UTC, jleach commented
@jlangy Just checking this PR is still valid after recent work?

2021-05-25 22:08 UTC, jlangy commented
Thanks for checking, PR #150 didn't adjust the template so this snapshot will still be good

2021-05-25 22:17 UTC, jleach approved these changes

2021-05-25 22:17 UTC, merged